In [21]:
from xgboost import XGBClassifier
from xgboost import plot_importance
from matplotlib import pyplot

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from numpy import sort
from sklearn.feature_selection import SelectFromModel

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from itertools import combinations

In [22]:
df = pd.read_csv("../QB-Train.csv")
df = df.drop(["year","name","college","position"],1)
df.head()
#377

height_in  weight_lbs  40yards  benchpress  vert_leap_in  broad_jump_in  \
0       75.1         211     5.19         NaN          27.0          102.0   
1       75.9         222     5.11         NaN          28.5          105.0   
2       74.6         211     4.98         NaN          31.5          108.0   
3       71.4         204     4.78         NaN          30.0          105.0   
4       75.5         220     4.92         NaN          30.5          107.0   

   shuttle  3cone drafted  
0     4.67   8.03       N  
1     4.38   7.80       Y  
2     4.36   7.69       Y  
3     4.67   8.25       N  
4     4.33   7.85       N

In [19]:
Y = df["drafted"]
Y = Y.replace("Y",1)
Y = Y.replace("N",0)

#X = df.drop(['weight_lbs', '3cone', 'Crec', 'Cyds', 'hasbling', 'hasawards', "drafted"], 1)
X = df.drop(["drafted"],1)
X.head()

height_in  weight_lbs  40yards  benchpress  vert_leap_in  broad_jump_in  \
0       75.1         211     5.19         NaN          27.0          102.0   
1       75.9         222     5.11         NaN          28.5          105.0   
2       74.6         211     4.98         NaN          31.5          108.0   
3       71.4         204     4.78         NaN          30.0          105.0   
4       75.5         220     4.92         NaN          30.5          107.0   

   shuttle  3cone  
0     4.67   8.03  
1     4.38   7.80  
2     4.36   7.69  
3     4.67   8.25  
4     4.33   7.85

In [20]:
# split data into train and test sets
seed = 777
test_size = 0.30
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)

# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print(accuracy)

Accuracy: 60.53%
0.6052631578947368


In [23]:
def accuracyfinder(features):
    accuras = []
    
    Y = features["drafted"]
    Y = Y.replace("Y",1)
    Y = Y.replace("N",0)

    X = features.drop(["drafted"], 1)
    
    columns = X.columns.tolist()
    
    for a in range(1,len(columns)):
        for x in list(combinations(columns,a)):
            
            X = features.drop(["drafted"], 1)
            X = X.drop(list(x),1)
            # split data into train and test sets
            seed = 777
            test_size = 0.30
            X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

            # fit model on training data
            model = XGBClassifier()
            model.fit(X_train, y_train)

            # make predictions for test data
            y_pred = model.predict(X_test)
            predictions = [round(value) for value in y_pred]

            # evaluate predictions
            accuracy = accuracy_score(y_test, predictions)
            accuras.append(accuracy * 100)
            print("Accuracy: %.2f%%" % (accuracy * 100.0), list(x))
    
    
    print(max(accuras))

In [24]:
accuracyfinder(df)

Accuracy: 56.14% ['height_in']
Accuracy: 57.02% ['weight_lbs']
Accuracy: 54.39% ['40yards']
Accuracy: 60.53% ['benchpress']
Accuracy: 62.28% ['vert_leap_in']
Accuracy: 62.28% ['broad_jump_in']
Accuracy: 63.16% ['shuttle']
Accuracy: 59.65% ['3cone']
Accuracy: 50.00% ['height_in', 'weight_lbs']
Accuracy: 51.75% ['height_in', '40yards']
Accuracy: 59.65% ['height_in', 'benchpress']
Accuracy: 56.14% ['height_in', 'vert_leap_in']
Accuracy: 63.16% ['height_in', 'broad_jump_in']
Accuracy: 58.77% ['height_in', 'shuttle']
Accuracy: 59.65% ['height_in', '3cone']
Accuracy: 50.00% ['weight_lbs', '40yards']
Accuracy: 56.14% ['weight_lbs', 'benchpress']
Accuracy: 60.53% ['weight_lbs', 'vert_leap_in']
Accuracy: 64.04% ['weight_lbs', 'broad_jump_in']
Accuracy: 59.65% ['weight_lbs', 'shuttle']
Accuracy: 55.26% ['weight_lbs', '3cone']
Accuracy: 55.26% ['40yards', 'benchpress']
Accuracy: 62.28% ['40yards', 'vert_leap_in']
Accuracy: 65.79% ['40yards', 'broad_jump_in']
Accuracy: 61.40% ['40yards', 'shuttle'

Accuracy: 59.65% ['weight_lbs', 'benchpress', 'shuttle', '3cone']
Accuracy: 67.54% ['weight_lbs', 'vert_leap_in', 'broad_jump_in', 'shuttle']
Accuracy: 63.16% ['weight_lbs', 'vert_leap_in', 'broad_jump_in', '3cone']
Accuracy: 57.89% ['weight_lbs', 'vert_leap_in', 'shuttle', '3cone']
Accuracy: 63.16% ['weight_lbs', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 57.89% ['40yards', 'benchpress', 'vert_leap_in', 'broad_jump_in']
Accuracy: 60.53% ['40yards', 'benchpress', 'vert_leap_in', 'shuttle']
Accuracy: 60.53% ['40yards', 'benchpress', 'vert_leap_in', '3cone']
Accuracy: 64.91% ['40yards', 'benchpress', 'broad_jump_in', 'shuttle']
Accuracy: 57.89% ['40yards', 'benchpress', 'broad_jump_in', '3cone']
Accuracy: 54.39% ['40yards', 'benchpress', 'shuttle', '3cone']
Accuracy: 62.28% ['40yards', 'vert_leap_in', 'broad_jump_in', 'shuttle']
Accuracy: 57.02% ['40yards', 'vert_leap_in', 'broad_jump_in', '3cone']
Accuracy: 60.53% ['40yards', 'vert_leap_in', 'shuttle', '3cone']
Accuracy: 66.67% ['40

Accuracy: 60.53% ['weight_lbs', '40yards', 'vert_leap_in', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 64.04% ['weight_lbs', 'benchpress', 'vert_leap_in', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 59.65% ['40yards', 'benchpress', 'vert_leap_in', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 58.77% ['height_in', 'weight_lbs', '40yards', 'benchpress', 'vert_leap_in', 'broad_jump_in', 'shuttle']
Accuracy: 50.88% ['height_in', 'weight_lbs', '40yards', 'benchpress', 'vert_leap_in', 'broad_jump_in', '3cone']
Accuracy: 50.88% ['height_in', 'weight_lbs', '40yards', 'benchpress', 'vert_leap_in', 'shuttle', '3cone']
Accuracy: 53.51% ['height_in', 'weight_lbs', '40yards', 'benchpress', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 53.51% ['height_in', 'weight_lbs', '40yards', 'vert_leap_in', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 46.49% ['height_in', 'weight_lbs', 'benchpress', 'vert_leap_in', 'broad_jump_in', 'shuttle', '3cone']
Accuracy: 57.02% ['height_in', '40yards', 'benchp

In [31]:
X["benchpress"] = X["benchpress"].fillna(value=0)
X["vert_leap_in"] = X["vert_leap_in"].fillna(value=0)
X["broad_jump_in"] = X["broad_jump_in"].fillna(value=0)
X["shuttle"] = X["shuttle"].fillna(value=100)
X["3cone"] = X["3cone"].fillna(value=100)
X["40yards"] = X["40yards"].fillna(value=100)
X.head()

height_in  weight_lbs  40yards  benchpress  vert_leap_in  broad_jump_in  \
0       75.1         211     5.19         0.0          27.0          102.0   
1       75.9         222     5.11         0.0          28.5          105.0   
2       74.6         211     4.98         0.0          31.5          108.0   
3       71.4         204     4.78         0.0          30.0          105.0   
4       75.5         220     4.92         0.0          30.5          107.0   

   shuttle  3cone  
0     4.67   8.03  
1     4.38   7.80  
2     4.36   7.69  
3     4.67   8.25  
4     4.33   7.85

In [32]:
# split data into train and test sets
seed = 777
test_size = 0.30
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)

# fit model on training data
model = XGBClassifier()
model.fit(X_train, y_train)

# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))
#.1 and 200

Accuracy: 61.40%


In [33]:
for i in range(0,len(X.columns)):
    print(X.columns[i], model.feature_importances_[i] * 100)

height_in 16.993597149848938
weight_lbs 13.229994475841522
40yards 14.814293384552002
benchpress 6.638520210981369
vert_leap_in 12.316888570785522
broad_jump_in 13.072329759597778
shuttle 11.061009019613266
3cone 11.87337040901184


In [35]:
thresholds = sort(model.feature_importances_)
for thresh in thresholds:
    # select features using threshold
    selection = SelectFromModel(model, threshold=thresh, prefit=True)
    select_X_train = selection.transform(X_train)
    # train model
    selection_model = XGBClassifier()
    selection_model.fit(select_X_train, y_train)
    # eval model
    select_X_test = selection.transform(X_test)
    y_pred = selection_model.predict(select_X_test)
    predictions = [round(value) for value in y_pred]
    accuracy = accuracy_score(y_test, predictions)
    print("Thresh=%.3f, n=%d, Accuracy: %.2f%%" % (thresh, select_X_train.shape[1], accuracy*100.0))
    print(select_X_train)

Thresh=0.066, n=8, Accuracy: 61.40%
[[ 76.13 217.     4.78 ... 113.     3.96   6.82]
 [ 75.   236.     5.26 ... 103.     4.61   7.66]
 [ 77.5  265.     4.83 ...   0.   100.   100.  ]
 ...
 [ 74.4  226.     4.95 ...  96.   100.   100.  ]
 [ 71.75 207.     4.68 ... 112.     4.03   6.75]
 [ 77.4  241.     5.1  ...   0.   100.   100.  ]]
Thresh=0.111, n=7, Accuracy: 59.65%
[[ 76.13 217.     4.78 ... 113.     3.96   6.82]
 [ 75.   236.     5.26 ... 103.     4.61   7.66]
 [ 77.5  265.     4.83 ...   0.   100.   100.  ]
 ...
 [ 74.4  226.     4.95 ...  96.   100.   100.  ]
 [ 71.75 207.     4.68 ... 112.     4.03   6.75]
 [ 77.4  241.     5.1  ...   0.   100.   100.  ]]
Thresh=0.119, n=6, Accuracy: 62.28%
[[ 76.13 217.     4.78  32.   113.     6.82]
 [ 75.   236.     5.26  31.   103.     7.66]
 [ 77.5  265.     4.83   0.     0.   100.  ]
 ...
 [ 74.4  226.     4.95  29.5   96.   100.  ]
 [ 71.75 207.     4.68  31.5  112.     6.75]
 [ 77.4  241.     5.1    0.     0.   100.  ]]
Thresh=0.123, n=